# Generated by Django 3.1.7 on 2021-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='summonerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonername', models.CharField(max_length=30)),
                ('region', models.CharField(default='br1', max_length=10)),
                ('summonerid', models.CharField(max_length=60)),
                ('accountid', models.CharField(max_length=60)),
            ],
        ),
    ]
